root: ./

redirects:  
    previous/page1: labs/ddhills-jatre.md
    activity/kifi-2021: labs/kifi-2021.md
    activity/anthill: labs/anthill.md
    activity/iruway: labs/iruway.md
    activity/ddhills-jatre: labs/ddhills-jatre.md
